import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/src/components/Navbar/nav";
import Sidebar from "@/src/components/Sidebar/Sidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className=" flex container">
          <Sidebar />
          <div className=" bg-pink-300/10 mt-5 container lg:min-w-[1270px] min-h-screen rounded-xl pt-16 px-7">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
